# Generated by Django 4.2.7 on 2023-11-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth_data',
            new_name='birth_date',
        ),
    ]
